name: CI-win

on: [push, pull_request]

jobs:
  run:
    runs-on: windows-latest

    env:
      OS: windows
      PYTHON: '3.12'
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: ‘2’

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        git --version
        curl -o git-installer.exe https://github.com/git-for-windows/git/releases/latest/download/Git-2.48.1-64-bit.exe
        git-installer.exe /SILENT
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt

    - name: Generate Report
      run: |
        python -m unittest discover tests "test_*.py"
